AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  url:
    Type: String
    NoEcho: true
  lifetime:
    Type: Number
  born:
    Type: String
  interval:
    Type: String
  tz:
    Type: String
  stackname:
    Type: String

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      CodeUri: build
      Handler: !Ref stackname
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          URL: !Ref url
          LIFETIME: !Ref lifetime
          BORN: !Ref born
          TZ: !Ref tz
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref interval

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: "cloudwatch-logs"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
